[target.thumbv7em-none-eabi]
runner = 'probe-rs run --chip STM32G474RETx --connect-under-reset --no-location'

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "debug"

[unstable]
build-std = ["core"]
build-std-features = ["panic_immediate_abort"]
